docker:
  compose:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      enabled: false
    otlp:
      tracing:
        endpoint: http://localhost:4317

  metrics:
    export:
      prometheus:
        enabled: true
