spring:
  docker:
    compose:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://my-tempo:9411/api/v2/spans

  metrics:
    export:
      prometheus:
        enabled: true
