spring:
  datasource:
    url: jdbc:h2:mem:settings-db;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
