spring:
  datasource:
    url: jdbc:h2:mem:settings-db;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info
