spring:
  datasource:
    url: jdbc:h2:mem:settings-db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8081

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://keycloak_web:8080/realms/settings-app
        jwk-set-uri: http://keycloak_web:8080/realms/settings-app/protocol/openid-connect/certs