spring:
  datasource:
    url: jdbc:h2:mem:settings-db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

  zipkin:
    endpoint: http://my-tempo:9411/api/v2/spans